export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_ITEM = "ADD_ITEM"

export const GET_ORDER = 'GET_ORDER';
export const ORDER_LOADING = 'ORDER_LOADING';
export const DELETE_ORDER = 'DELETE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER'

export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = "ADD_PRODUCT";

export const GET_CATEGORY = 'GET_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';

export const ADD_PREORDER = "ADD_PREORDER";
export const GET_PREORDER = "GET_PREORDER";
export const GET_PREORDER_BYTABLE = "GET_PREORDER_BYTABLE";
export const DELET_PREORDER = "DELETE_PREORDER";
export const PUT_PREORDER = "PUT_PREORDER";
export const PUT_PREORDER_SUCCESS = "PUT_PREORDER_SUCCESS";

