export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_ITEM = "ADD_ITEM"

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_BY_DATE = 'GET_ORDER_BY_DATE';
export const GET_ORDER_BY_DATE_FT = 'GET_ORDER_BY_DATE_FT';
export const ORDER_LOADING = 'ORDER_LOADING';
export const DELETE_ORDER = 'DELETE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const CHECK_CATEGORY = 'CHECK_CATEGORY';

export const GET_PRODUCT = 'GET_PRODUCT'; 
export const GET_PRODUCT_BREAKFAST = 'GET_PRODUCT_BREAKFAST'; 
export const GET_PRODUCT_MEAL = 'GET_PRODUCT_MEAL'; 
export const GET_PRODUCT_DINNER = 'GET_PRODUCT_DINNER'; 
export const GET_PRODUCT_DRINK = 'GET_PRODUCT_DRINK'; 
export const GET_PRODUCT_DESSERT = 'GET_PRODUCT_DESSERT'; 
export const GET_PRODUCT_CASHIER = 'GET_PRODUCT_CASHIER';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = "ADD_PRODUCT";

export const GET_CATEGORY = 'GET_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';

export const ADD_PREORDER = "ADD_PREORDER";
export const ADD_DRINK = "ADD_DRINK";
export const GET_PREORDER = "GET_PREORDER";
export const GET_PREORDER_BYTABLE = "GET_PREORDER_BYTABLE";
export const GET_PREORDER_BYTABLE_WAITER = "GET_PREORDER_BYTABLE_WAITER"
export const DELET_PREORDER = "DELETE_PREORDER";
export const PUT_PREORDER = "PUT_PREORDER";
export const PUT_PREORDER_SUCCESS = "PUT_PREORDER_SUCCESS";
export const GET_PREORDER_BYTABLE_FINISHED_DELIVERED = "GET_PREORDER_BYTABLE_FINISHED_DELIVERED"

export const GET_ID_ORDER = "GET_ID_ORDER";

export const GET_TABLE1 = "GET_TABLE1";
export const GET_TABLE2 = "GET_TABLE2";
export const GET_TABLE3 = "GET_TABLE3";
export const GET_TABLE4 = "GET_TABLE4";
export const GET_TABLE5 = "GET_TABLE5";
export const GET_TABLE6 = "GET_TABLE6";

export const GET_ERRORS = "GET_ERRORS";
export const GET_REGISTER_RIGHT = "GET_REGISTER_RIGHT";
export const SET_CURRENT_USER ="SET_CURRENT_USER";
export const GET_USERS ="GET_USERS";
export const DELETE_USER = "DELETE_USER";

export const GET_TABLE1_FINISHED = "GET_TABLE1_FINISHED"
export const GET_TABLE2_FINISHED = "GET_TABLE2_FINISHED"
export const GET_TABLE3_FINISHED = "GET_TABLE3_FINISHED"
export const GET_TABLE4_FINISHED = "GET_TABLE4_FINISHED"
export const GET_TABLE5_FINISHED = "GET_TABLE5_FINISHED"
export const GET_TABLE6_FINISHED = "GET_TABLE6_FINISHED"


export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_ID = "GET_INGREDIENTS_ID"
export const POST_INGREDIENTS = "POST_INGREDINTS"
export const INGREDIENTS_LOADING = "INGREDIENTS_LOADING"

